"""empty message

Revision ID: 300535497a4c
Revises: 2b8bbb2665a5
Create Date: 2025-01-26 15:41:42.302676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300535497a4c'
down_revision = '2b8bbb2665a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_favourites_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('people_favourites_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('planet_favourites_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['users_favourites_id'], ['id'])
        batch_op.create_foreign_key(None, 'people', ['people_favourites_id'], ['id'])
        batch_op.create_foreign_key(None, 'planets', ['planet_favourites_id'], ['id'])

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'planets', ['homeworld_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('homeworld_id')

    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planet_favourites_id')
        batch_op.drop_column('people_favourites_id')
        batch_op.drop_column('users_favourites_id')

    # ### end Alembic commands ###
