"""empty message

Revision ID: d6c055451e82
Revises: 300535497a4c
Create Date: 2025-01-26 15:47:05.684278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c055451e82'
down_revision = '300535497a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.alter_column('people_favourites_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planet_favourites_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('homeworld_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('homeworld_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.alter_column('planet_favourites_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('people_favourites_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
